
version: "2"

volumes:
  db-data:
    external: false

services:
  prod_db:
    image: postgres
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  prod_app:
    build: .
    env_file: .env.prod
    ports:
      - "3000:3000"
    depends_on:
    - prod_db