
version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env
    volumes:
      - .:/Users/rajkiran/Desktop/ror/meal_plan/app
    ports:
      - "3000:3000"
    depends_on:
    - db